name: Security Pipeline

on:
  push:
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Dependency validation (npm audit)
        run: npm audit --audit-level=high

      # Aquí ya NO hay CodeQL

      - name: Build project
        run: npm run build --if-present

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: "."
          severity: CRITICAL,HIGH
          exit-code: "1"

      - name: Build Docker image
        run: docker build -t water-management:latest .

      - name: Trivy container scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: water-management:latest
          severity: CRITICAL,HIGH
          exit-code: "1"
